# Generated by Django 5.2.12 on 2026-03-24 14:02

import apps.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0002_event_location_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="cover_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="events/",
                validators=[apps.core.validators.ImageFileValidator()],
            ),
        ),
    ]
