# Generated by Django 5.2.12 on 2026-03-24 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0003_alter_event_cover_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="sales_cutoff_hours",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Encerra vendas N horas antes do início do evento. Nulo = sem encerramento antecipado.",
                null=True,
            ),
        ),
    ]
