# Generated by Django 4.2.5 on 2026-07-15 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0004_event_sales_cutoff_hours"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="event",
            index=models.Index(
                fields=["status", "start_date"], name="events_even_status_dfba18_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(fields=["city"], name="events_even_city_533bd7_idx"),
        ),
    ]
