# Generated by Django 4.2.5 on 2026-04-01 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_order_payment_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="payment_attempts",
            field=models.PositiveSmallIntegerField(
                default=0, help_text="Number of payment attempts made."
            ),
        ),
    ]
