# Generated by Django 4.2.5 on 2026-04-05 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_order_payment_attempts"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="reminder_sent_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Timestamp do último e-mail de lembrete enviado. Impede spam de reenvios.",
                null=True,
            ),
        ),
    ]
