# Generated by Django 4.2.5 on 2026-07-15 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0004_add_reminder_sent_at_to_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="mp_order_id",
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["status", "expires_at"], name="orders_orde_status_62907b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["buyer", "-created_at"], name="orders_orde_buyer_i_67c51b_idx"
            ),
        ),
    ]
