# Generated by Django 4.2.5 on 2026-04-01 22:41

import apps.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="cpf",
            field=models.CharField(
                blank=True,
                help_text="CPF no formato 000.000.000-00",
                max_length=14,
                null=True,
                unique=True,
                validators=[apps.core.validators.validate_cpf],
                verbose_name="CPF",
            ),
        ),
    ]
