# Generated by Django 5.2.12 on 2026-03-21 22:59

import apps.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0002_plan_companysubscription"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="logo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="logos/",
                validators=[apps.core.validators.ImageFileValidator()],
            ),
        ),
    ]
