# Generated by Django 4.2.5 on 2026-04-01 22:42

import apps.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0003_alter_company_logo"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="responsible_cpf",
            field=models.CharField(
                blank=True,
                max_length=14,
                null=True,
                validators=[apps.core.validators.validate_cpf],
                verbose_name="CPF do responsável",
            ),
        ),
    ]
