# Generated by Django 4.2.5 on 2026-04-07 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0004_company_responsible_cpf"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="pix_key",
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Chave PIX"),
        ),
        migrations.AddField(
            model_name="company",
            name="pix_key_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("cpf", "CPF"),
                    ("cnpj", "CNPJ"),
                    ("email", "E-mail"),
                    ("phone", "Telefone"),
                    ("random", "Chave aleatória"),
                ],
                max_length=20,
                null=True,
                verbose_name="Tipo de chave PIX",
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="responsible_cnpj",
            field=models.CharField(
                blank=True, max_length=18, null=True, verbose_name="CNPJ do responsável"
            ),
        ),
    ]
