# Generated by Django 5.2.12 on 2026-03-21 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0003_tickettransfer_platform_fee"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tickettransfer",
            name="platform_fee",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="8% platform fee on the agreed_price. Total receiver pays = agreed_price + platform_fee.",
                max_digits=10,
                null=True,
            ),
        ),
    ]
