# Generated by Django 4.2.5 on 2026-04-01 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_order_payment_attempts"),
        ("tickets", "0004_alter_tickettransfer_platform_fee"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tickets",
                to="orders.order",
            ),
        ),
    ]
