# Generated by Django 4.2.5 on 2026-07-15 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0005_add_order_fk_to_ticket"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tickettransfer",
            name="to_email",
            field=models.EmailField(db_index=True, max_length=254),
        ),
        migrations.AddIndex(
            model_name="ticket",
            index=models.Index(fields=["owner", "status"], name="tickets_tic_owner_i_70fd59_idx"),
        ),
        migrations.AddIndex(
            model_name="ticket",
            index=models.Index(fields=["event", "status"], name="tickets_tic_event_i_d07e31_idx"),
        ),
    ]
