# Generated by Django 4.2.5 on 2026-04-07 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("withdrawals", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="withdrawal",
            name="pix_key_type",
            field=models.CharField(
                choices=[
                    ("cpf", "CPF"),
                    ("cnpj", "CNPJ"),
                    ("email", "E-mail"),
                    ("phone", "Telefone"),
                    ("random", "Chave aleatória"),
                ],
                max_length=20,
            ),
        ),
    ]
