# Generated by Django 4.2.5 on 2026-07-15 01:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("withdrawals", "0002_alter_withdrawal_pix_key_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="withdrawal",
            name="reviewed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="withdrawal",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Admin da plataforma que aprovou/rejeitou o saque.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="withdrawals_reviewed",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="withdrawal",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Aguardando aprovação"),
                    ("approved", "Aprovado — aguardando envio"),
                    ("processing", "Processando"),
                    ("completed", "Concluído"),
                    ("failed", "Falhou"),
                    ("rejected", "Rejeitado"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
